CREATE TABLE TB_INSUMOS (
  ID_INSUMO SERIAL,
  NOME_INSUMO VARCHAR(45) NOT NULL,
  TIPO VARCHAR(45) NOT NULL,
  DESCRICAO_INSUMO TEXT NULL,
  PRINCIPIO_ATIVO VARCHAR(45) NOT NULL,
  PRECO_INSUMO DECIMAL(10,2) NOT NULL,
  CONSTRAINT PK_TB_INSUMOS PRIMARY KEY (ID_INSUMO)
);



CREATE TABLE TB_FUNCIONARIOS (
  CPF_FUNCIONARIO VARCHAR(11) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  DT_NASC DATE NOT NULL,
  DT_ADMISSAO DATE NOT NULL,
  CTPS VARCHAR(15) NOT NULL,
  CARGO VARCHAR(45) NOT NULL,
  SALARIO DECIMAL(10,2) NOT NULL,
  ESTADO_CIVIL VARCHAR(15) NOT NULL,
  FERIAS BOOLEAN NOT NULL,
  TELEFONE VARCHAR(11) NULL,
  SEXO CHAR(1) NOT NULL,
  EMAIL VARCHAR(45) NULL,
  CONSTRAINT PK_TB_FUNCIONARIOS PRIMARY KEY (CPF_FUNCIONARIO)
);



CREATE TABLE TB_REMEDIOS (
  ID_REMEDIO SERIAL,
  NOME_REMEDIO VARCHAR(45) NOT NULL,
  DESCRICAO_REMEDIO TEXT NULL,
  PRECO_TABELA DECIMAL(10,2) NOT NULL,
  QTD_PRODUZIDA INT NOT NULL,
  FUNCIONARIO_CPF_FUNCIONARIO VARCHAR(11) NOT NULL,
  CONSTRAINT PK_TB_REMEDIOS PRIMARY KEY (ID_REMEDIO),
  CONSTRAINT FK_TB_REMEDIOS_TB_FUNCIONARIOS FOREIGN KEY (FUNCIONARIO_CPF_FUNCIONARIO)
    REFERENCES TB_FUNCIONARIOS (CPF_FUNCIONARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_ESTOQUES (
  ID_ESTOQUE SERIAL,
  QTD_ESTOQUE INT NOT NULL,
  PRECO_CUSTO DECIMAL(10,2) NOT NULL,
  PRECO_VENDA DECIMAL(10,2) NOT NULL,
  DATA_VALIDADE DATE NOT NULL,
  LOTE VARCHAR(30) NOT NULL,
  INSUMO_ID_INSUMO INT NOT NULL,
  REMEDIO_ID_REMEDIO INT NOT NULL,
  CONSTRAINT PK_TB_ESTOQUES PRIMARY KEY (ID_ESTOQUE),
  CONSTRAINT FK_TB_ESTOQUES_TB_INSUMOS FOREIGN KEY (INSUMO_ID_INSUMO)
    REFERENCES TB_INSUMOS (ID_INSUMO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_ESTOQUES_TB_REMEDIOS FOREIGN KEY (REMEDIO_ID_REMEDIO)
    REFERENCES TB_REMEDIOS (ID_REMEDIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_CONVENIOS (
  ID_CONVENIO SERIAL,
  NOME VARCHAR(45) NOT NULL,
  DESCRICAO_CONVENIO TEXT NULL,
  VALOR_DESCONTO DECIMAL(10,2) NOT NULL,
  CONSTRAINT PK_TB_CONVENIOS PRIMARY KEY (ID_CONVENIO)
);



CREATE TABLE TB_CLIENTES (
  CPF_CNPJ_CLIENTE VARCHAR(14) NOT NULL,
  NOME_CLIENTE VARCHAR(100) NOT NULL,
  DATA_NASCIMENTO DATE NOT NULL,
  SEXO CHAR(1) NOT NULL,
  TELEFONE VARCHAR(11) NULL,
  EMAIL VARCHAR(45) NULL,
  CONVENIO_ID_CONVENIO INT NOT NULL,
  CONSTRAINT PK_TB_CLIENTES PRIMARY KEY (CPF_CNPJ_CLIENTE),
  CONSTRAINT FK_TB_CLIENTES_TB_CONVENIOS FOREIGN KEY (CONVENIO_ID_CONVENIO)
    REFERENCES TB_CONVENIOS (ID_CONVENIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_TERCEIROS (
  CPF_CNPJ_TERCEIRO VARCHAR(14) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  CODIGO_RASTREIO VARCHAR(45) NULL,
  TIPO_VEICULO VARCHAR(20) NOT NULL,
  PLACA_VEICULO CHAR(7) NOT NULL,
  TELEFONE VARCHAR(11) NULL,
  CONSTRAINT PK_TB_TERCEIROS PRIMARY KEY (CPF_CNPJ_TERCEIRO)
);



CREATE TABLE TB_VENDAS (
  ID_VENDA SERIAL,
  VALOR_TOTAL DECIMAL(10,2) NOT NULL,
  DATA_VENDA DATE NOT NULL,
  NF_VENDA VARCHAR(45) NOT NULL,
  STATUS_PAG BOOLEAN NOT NULL,
  STATUS_ENTREGA BOOLEAN NOT NULL,
  CLIENTE_CPF_CNPJ_CLIENTE VARCHAR(14) NOT NULL,
  FUNCIONARIO_CPF_FUNCIONARIO VARCHAR(11) NOT NULL,
  TERCEIRO_CPF_CNPJ_TERCEIRO VARCHAR(14) NOT NULL,
  CONVENIO_ID_CONVENIO INT NOT NULL,
  CONSTRAINT PK_TB_VENDAS PRIMARY KEY (ID_VENDA),
  CONSTRAINT FK_TB_VENDAS_TB_CLIENTES FOREIGN KEY (CLIENTE_CPF_CNPJ_CLIENTE)
    REFERENCES TB_CLIENTES (CPF_CNPJ_CLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_VENDAS_TB_FUNCIONARIOS FOREIGN KEY (FUNCIONARIO_CPF_FUNCIONARIO)
    REFERENCES TB_FUNCIONARIOS (CPF_FUNCIONARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_VENDAS_TB_TERCEIROS FOREIGN KEY (TERCEIRO_CPF_CNPJ_TERCEIRO)
    REFERENCES TB_TERCEIROS (CPF_CNPJ_TERCEIRO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_VENDAS_TB_CONVENIOS FOREIGN KEY (CONVENIO_ID_CONVENIO)
    REFERENCES TB_CONVENIOS (ID_CONVENIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_FORNECEDORES (
  CNPJ_FORNECEDOR VARCHAR(14) NOT NULL,
  NOME_FORNECEDOR VARCHAR(100) NOT NULL,
  TELEFONE VARCHAR(11) NULL,
  EMAIL VARCHAR(45) NULL,
  CONSTRAINT PK_TB_FORNECEDORES PRIMARY KEY (CNPJ_FORNECEDOR)
);



CREATE TABLE TB_COMPRAS (
  ID_COMPRA SERIAL,
  DATA_COMPRA DATE NOT NULL,
  STATUS_COMPRA BOOLEAN NOT NULL,
  QUANTIDADE INT NOT NULL,
  STATUS_ENTREGA BOOLEAN NOT NULL,
  VALOT_TOTAL DECIMAL(10,2) NOT NULL,
  FUNCIONARIO_CPF_FUNCIONARIO VARCHAR(11) NOT NULL,
  NF_COMPRA VARCHAR(45) NULL,
  FORNECEDOR_CNPJ_FORNECEDOR VARCHAR(14) NOT NULL,
  CONSTRAINT PK_TB_COMPRAS PRIMARY KEY (ID_COMPRA),
  CONSTRAINT FK_TB_COMPRAS_TB_FUNCIONARIOS FOREIGN KEY (FUNCIONARIO_CPF_FUNCIONARIO)
    REFERENCES TB_FUNCIONARIOS (CPF_FUNCIONARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_COMPRAS_TB_FORNECEDORES FOREIGN KEY (FORNECEDOR_CNPJ_FORNECEDOR)
    REFERENCES TB_FORNECEDORES (CNPJ_FORNECEDOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_MEDICOS (
  CRM_MEDICO VARCHAR(15) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  ESPECIALIDADE VARCHAR(45) NOT NULL,
  TELEFONE VARCHAR(11) NULL,
  EMAIL VARCHAR(45) NULL,
  CONSTRAINT PK_TB_MEDICOS PRIMARY KEY (CRM_MEDICO)
);



CREATE TABLE TB_RECEITAS (
  ID_RECEITA SERIAL,
  DATA_PRESCRICAO DATE NOT NULL,
  VALIDADE_RECEITA DATE NOT NULL,
  CLIENTE_CPF_CNPJ_CLIENTE VARCHAR(14) NOT NULL,
  MEDICO_CRM_MEDICO VARCHAR(15) NOT NULL,
  VENDA_ID_VENDA INT NOT NULL,
  MEDICAMENTO TEXT NOT NULL,
  CONSTRAINT PK_TB_RECEITAS PRIMARY KEY (ID_RECEITA),
  CONSTRAINT FK_TB_RECEITAS_TB_CLIENTES FOREIGN KEY (CLIENTE_CPF_CNPJ_CLIENTE)
    REFERENCES TB_CLIENTES (CPF_CNPJ_CLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_RECEITAS_TB_MEDICOS FOREIGN KEY (MEDICO_CRM_MEDICO)
    REFERENCES TB_MEDICOS (CRM_MEDICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_RECEITAS_TB_VENDAS FOREIGN KEY (VENDA_ID_VENDA)
    REFERENCES TB_VENDAS (ID_VENDA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_ENDERECOS (
  ID_ENDERECO SERIAL,
  TIPO_LOGRADOURO VARCHAR(20) NOT NULL,
  NOME_RUA VARCHAR(100) NOT NULL,
  NUMERO int NOT NULL,
  COMPLEMENTO VARCHAR(50) NULL,
  BAIRRO VARCHAR(100) NOT NULL,
  CIDADE VARCHAR(100) NOT NULL,
  ESTADO CHAR(2) NOT NULL,
  CEP VARCHAR(8) NOT NULL,
  FORNECEDOR_CNPJ_FORNECEDOR VARCHAR(14)  NULL,
  FUNCIONARIO_CPF_FUNCIONARIO VARCHAR(11)  NULL,
  CLIENTE_CPF_CNPJ_CLIENTE VARCHAR(14)  NULL,
  MEDICO_CRM_MEDICO VARCHAR(15)  NULL,
  CONSTRAINT PK_TB_ENDERECOS PRIMARY KEY (ID_ENDERECO),
  CONSTRAINT FK_TB_ENDERECOS_TB_FORNECEDORES FOREIGN KEY (FORNECEDOR_CNPJ_FORNECEDOR)
    REFERENCES TB_FORNECEDORES (CNPJ_FORNECEDOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_ENDERECOS_TB_FUNCIONARIOS FOREIGN KEY (FUNCIONARIO_CPF_FUNCIONARIO)
    REFERENCES TB_FUNCIONARIOS (CPF_FUNCIONARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_ENDERECOS_TB_CLIENTES FOREIGN KEY (CLIENTE_CPF_CNPJ_CLIENTE)
    REFERENCES TB_CLIENTES (CPF_CNPJ_CLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_ENDERECOS_TB_MEDICOS FOREIGN KEY (MEDICO_CRM_MEDICO)
    REFERENCES TB_MEDICOS (CRM_MEDICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_CONVENIOS_HAS_TB_MEDICOS (
  CONVENIO_ID_CONVENIO SERIAL,
  MEDICO_CRM_MEDICO VARCHAR(15) NOT NULL,
  CONSTRAINT PK_TB_CONVENIOS_HAS_TB_MEDICOS PRIMARY KEY (CONVENIO_ID_CONVENIO, MEDICO_CRM_MEDICO),
  CONSTRAINT FK_TB_CONVENIOS_HAS_TB_MEDICOS_TB_CONVENIOS FOREIGN KEY (CONVENIO_ID_CONVENIO)
    REFERENCES TB_CONVENIOS (ID_CONVENIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_CONVENIOS_HAS_TB_MEDICOS_TB_MEDICOS FOREIGN KEY (MEDICO_CRM_MEDICO)
    REFERENCES TB_MEDICOS (CRM_MEDICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_INSUMOS_HAS_TB_FORNECEDORES (
  INSUMO_ID_INSUMO SERIAL,
  FORNECEDOR_CNPJ_FORNECEDOR VARCHAR(14) NOT NULL,
  CONSTRAINT PK_TB_INSUMOS_HAS_TB_FORNECEDORES PRIMARY KEY (INSUMO_ID_INSUMO, FORNECEDOR_CNPJ_FORNECEDOR),
  CONSTRAINT FK_TB_INSUMOS_HAS_TB_FORNECEDORES_TB_INSUMOS FOREIGN KEY (INSUMO_ID_INSUMO)
    REFERENCES TB_INSUMOS (ID_INSUMO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_INSUMOS_HAS_TB_FORNECEDORES_TB_FORNECEDORES FOREIGN KEY (FORNECEDOR_CNPJ_FORNECEDOR)
    REFERENCES TB_FORNECEDORES (CNPJ_FORNECEDOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_REMEDIOS_HAS_TB_INSUMOS (
  REMEDIO_ID_REMEDIO SERIAL,
  INSUMO_ID_INSUMO SERIAL,
  QTD_INSUMO INT NOT NULL,
  CONSTRAINT PK_TB_REMEDIOS_HAS_TB_INSUMOS PRIMARY KEY (REMEDIO_ID_REMEDIO, INSUMO_ID_INSUMO),
  CONSTRAINT FK_TB_REMEDIOS_HAS_TB_INSUMOS_TB_REMEDIOS FOREIGN KEY (REMEDIO_ID_REMEDIO)
    REFERENCES TB_REMEDIOS (ID_REMEDIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_REMEDIOS_HAS_TB_INSUMOS_TB_INSUMOS FOREIGN KEY (INSUMO_ID_INSUMO)
    REFERENCES TB_INSUMOS (ID_INSUMO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_INSUMOS_HAS_TB_COMPRAS (
  INSUMO_ID_INSUMO SERIAL,
  COMPRA_ID_COMPRA SERIAL,
  QTD_INSUMOS INT NULL,
  PRECO_INSUMO DECIMAL(10,2) NOT NULL,
  CONSTRAINT PK_TB_INSUMOS_HAS_TB_COMPRAS PRIMARY KEY (INSUMO_ID_INSUMO, COMPRA_ID_COMPRA),
  CONSTRAINT FK_TB_INSUMOS_HAS_TB_COMPRAS_TB_INSUMOS FOREIGN KEY (INSUMO_ID_INSUMO)
    REFERENCES TB_INSUMOS (ID_INSUMO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_INSUMOS_HAS_TB_COMPRAS_TB_COMPRAS FOREIGN KEY (COMPRA_ID_COMPRA)
    REFERENCES TB_COMPRAS (ID_COMPRA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



CREATE TABLE TB_REMEDIOS_HAS_TB_VENDAS (
  REMEDIO_ID_REMEDIO SERIAL,
  VENDA_ID_VENDA SERIAL,
  QTD_REMEDIO INT NOT NULL,
  PRECO_REMEDIO DECIMAL(10,2) NOT NULL,
  CONSTRAINT PK_TB_REMEDIOS_HAS_TB_VENDAS PRIMARY KEY (REMEDIO_ID_REMEDIO, VENDA_ID_VENDA),
  CONSTRAINT FK_TB_REMEDIOS_HAS_TB_VENDAS_TB_REMEDIOS FOREIGN KEY (REMEDIO_ID_REMEDIO)
    REFERENCES TB_REMEDIOS (ID_REMEDIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_REMEDIOS_HAS_TB_VENDAS_TB_VENDAS FOREIGN KEY (VENDA_ID_VENDA)
    REFERENCES TB_VENDAS (ID_VENDA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

